const { Types } = require("mongoose");
const { CourseTierCutoff, Programme, Institution, InstitutionProgramme, AdmissionRule, AdmissionSession } = require("../models");
const auditService = require("./audit.service");
const { NotFoundError, ValidationAppError } = require("../errors/AppError");
const { RESOURCE_TYPES, INSTITUTION_TIERS, RECORD_STATUS, RULE_STATUS } = require("../config/constants");
const { isStillAutoGenerated, nearestInstitutionTier, resolveDefaultSession } = require("../utils/cutoffCoverage");
const { normalizeCourseName } = require("../utils/courseName");

const VALID_TIERS = new Set(INSTITUTION_TIERS.map((t) => t.index));
const TIER_LABEL_BY_INDEX = new Map(INSTITUTION_TIERS.map((t) => [t.index, t.label]));

async function listForProgramme(programmeId) {
  return CourseTierCutoff.find({ programme: programmeId }).sort({ institutionTier: -1 }).lean();
}

async function upsertForProgramme(programmeId, cutoffs, actor, req) {
  const programme = await Programme.findById(programmeId);
  if (!programme) throw new NotFoundError("Programme not found");

  for (const entry of cutoffs) {
    if (!VALID_TIERS.has(entry.institutionTier)) {
      throw new ValidationAppError(`institutionTier ${entry.institutionTier} is not a recognised tier`);
    }

    if (entry.cutoffMark === null) {
      const removed = await CourseTierCutoff.findOneAndDelete({ programme: programmeId, institutionTier: entry.institutionTier });
      if (removed) {
        await auditService.record({
          user: actor._id,
          action: "COURSE_TIER_CUTOFF_CLEARED",
          resourceType: RESOURCE_TYPES.COURSE_TIER_CUTOFF,
          resourceId: removed._id,
          previousValue: removed,
          req,
        });
      }
      continue;
    }

    const previous = await CourseTierCutoff.findOne({ programme: programmeId, institutionTier: entry.institutionTier }).lean();
    const doc = await CourseTierCutoff.findOneAndUpdate(
      { programme: programmeId, institutionTier: entry.institutionTier },
      { $set: { cutoffMark: entry.cutoffMark, notes: entry.notes, updatedBy: actor._id } },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    await auditService.record({
      user: actor._id,
      action: previous ? "COURSE_TIER_CUTOFF_UPDATED" : "COURSE_TIER_CUTOFF_CREATED",
      resourceType: RESOURCE_TYPES.COURSE_TIER_CUTOFF,
      resourceId: doc._id,
      previousValue: previous,
      newValue: { cutoffMark: entry.cutoffMark, notes: entry.notes },
      req,
    });
  }

  return listForProgramme(programmeId);
}

async function summary({ programmeIds } = {}) {
  const match = programmeIds?.length ? { programme: { $in: programmeIds.map((id) => new Types.ObjectId(id)) } } : {};
  const rows = await CourseTierCutoff.aggregate([{ $match: match }, { $group: { _id: "$programme", count: { $sum: 1 } } }]);
  const byProgramme = {};
  rows.forEach((r) => {
    byProgramme[String(r._id)] = r.count;
  });
  return {
    tierCount: VALID_TIERS.size,
    programmesWithAnyCutoff: rows.length,
    totalCutoffs: rows.reduce((sum, r) => sum + r.count, 0),
    byProgramme,
  };
}

// Offerings that fall in the crack: neither a real per-institution rule nor
// a matrix entry for their (programme, institution tier) covers them. This
// happens when one institution in a tier offers a course no other
// institution in that tier does — e.g. OAU offers Marine Engineering but
// UNILAG (also Tier 1 Federal) doesn't, so a matrix cell built off UNILAG's
// course list never gets created for it, and it silently falls back to the
// synthetic formula unless someone notices. Grouped by (programme, tier)
// rather than listed per-offering since one matrix entry would resolve the
// whole group at once.
async function gaps({ institutionTier, search, page = 1, limit = 20, admissionSession } = {}) {
  const session = await resolveDefaultSession(AdmissionSession, admissionSession);

  const [offerings, institutions, programmes, existingRules, matrixRows] = await Promise.all([
    InstitutionProgramme.find({ status: RECORD_STATUS.ACTIVE }, { institution: 1, programme: 1 }).lean(),
    Institution.find({}, { name: 1, metadata: 1 }).lean(),
    Programme.find({}, { name: 1, faculty: 1 }).lean(),
    session
      ? AdmissionRule.find(
          { admissionSession: session._id, status: RULE_STATUS.PUBLISHED },
          { institution: 1, programme: 1, source: 1, verification: 1 }
        ).lean()
      : [],
    CourseTierCutoff.find({}, { programme: 1, institutionTier: 1 }).lean(),
  ]);

  const institutionById = new Map(institutions.map((i) => [String(i._id), i]));
  const programmeById = new Map(programmes.map((p) => [String(p._id), p]));
  const manualByKey = new Set(
    existingRules.filter((r) => !isStillAutoGenerated(r)).map((r) => `${r.institution}:${r.programme}`)
  );
  const matrixSet = new Set(matrixRows.map((m) => `${m.programme}:${m.institutionTier}`));

  const groups = new Map();
  for (const offering of offerings) {
    const institution = institutionById.get(String(offering.institution));
    const programme = programmeById.get(String(offering.programme));
    if (!institution || !programme) continue;

    if (manualByKey.has(`${offering.institution}:${offering.programme}`)) continue;

    const tier = nearestInstitutionTier(institution.metadata?.competitivenessIndex);
    if (tier === null) continue; // unrated institutions sit outside the tier-matrix model

    if (matrixSet.has(`${offering.programme}:${tier}`)) continue;

    const groupKey = `${offering.programme}:${tier}`;
    if (!groups.has(groupKey)) {
      groups.set(groupKey, {
        programmeId: String(offering.programme),
        programmeName: programme.name,
        faculty: programme.faculty || "",
        institutionTier: tier,
        tierLabel: TIER_LABEL_BY_INDEX.get(tier),
        institutions: [],
      });
    }
    groups.get(groupKey).institutions.push({ id: String(offering.institution), name: institution.name });
  }

  let items = Array.from(groups.values());
  if (institutionTier !== undefined) items = items.filter((g) => g.institutionTier === institutionTier);
  if (search) {
    const q = search.toLowerCase();
    items = items.filter((g) => g.programmeName.toLowerCase().includes(q) || g.faculty.toLowerCase().includes(q));
  }
  items.sort((a, b) => b.institutionTier - a.institutionTier || a.programmeName.localeCompare(b.programmeName));

  const total = items.length;
  const totalOfferings = items.reduce((sum, g) => sum + g.institutions.length, 0);
  const skip = (page - 1) * limit;

  return {
    items: items.slice(skip, skip + limit),
    total,
    totalOfferings,
    admissionSession: session ? { id: session._id, name: session.name } : null,
  };
}

// One institution's course list with each course's cutoff status, filtered
// by that institution's own tier:
//  - manual  the institution has its own published/verified rule
//  - matrix  a curated CourseTierCutoff entry already covers (programme, tier)
//  - auto    no rule/matrix entry exists yet, but a sibling institution in the
//            SAME tier has a manual cutoff for the SAME programme (matchedBy:
//            "id") or for a differently-spelled Programme catalog row that
//            normalizes to the same course name (matchedBy: "name" — e.g.
//            "Medicine and Surgery" vs "Medicine & Surgery") — that value is
//            adopted and persisted as the matrix entry right here, so this
//            gap never has to be noticed and closed by hand
//  - unmatched  no sibling in the tier offers this course either; needs an
//               admin-typed cutoff (or stays on the synthetic formula)
async function listForInstitution(institutionId, { search, page = 1, limit = 20 } = {}, actor, req) {
  const institution = await Institution.findById(institutionId).lean();
  if (!institution) throw new NotFoundError("Institution not found");

  const tier = nearestInstitutionTier(institution.metadata?.competitivenessIndex);
  const session = await resolveDefaultSession(AdmissionSession);

  const [myOfferings, programmes, institutions, matrixRows, publishedRules] = await Promise.all([
    InstitutionProgramme.find({ institution: institutionId, status: RECORD_STATUS.ACTIVE }, { programme: 1 }).lean(),
    Programme.find({}, { name: 1, faculty: 1 }).lean(),
    Institution.find({}, { name: 1, metadata: 1 }).lean(),
    CourseTierCutoff.find({}, { programme: 1, institutionTier: 1, cutoffMark: 1 }).lean(),
    session
      ? AdmissionRule.find(
          { admissionSession: session._id, status: RULE_STATUS.PUBLISHED },
          { institution: 1, programme: 1, source: 1, verification: 1, utme: 1 }
        ).lean()
      : [],
  ]);

  const programmeById = new Map(programmes.map((p) => [String(p._id), p]));
  const institutionById = new Map(institutions.map((i) => [String(i._id), i]));
  const matrixByKey = new Map(matrixRows.map((m) => [`${m.programme}:${m.institutionTier}`, m.cutoffMark]));

  const manualRules = publishedRules.filter((r) => !isStillAutoGenerated(r));
  const ownManualByProgramme = new Map(
    manualRules.filter((r) => String(r.institution) === String(institutionId)).map((r) => [String(r.programme), r])
  );

  const sameTierInstitutionIds = new Set(
    institutions
      .filter(
        (i) => String(i._id) !== String(institutionId) && nearestInstitutionTier(i.metadata?.competitivenessIndex) === tier
      )
      .map((i) => String(i._id))
  );
  const normalizedNameByProgrammeId = new Map(programmes.map((p) => [String(p._id), normalizeCourseName(p.name)]));

  const siblingManualByProgramme = new Map();
  const siblingManualByName = new Map();
  for (const rule of manualRules) {
    const instId = String(rule.institution);
    if (!sameTierInstitutionIds.has(instId)) continue;
    const progId = String(rule.programme);
    const entry = { rule, institution: institutionById.get(instId), programme: programmeById.get(progId) };

    if (!siblingManualByProgramme.has(progId)) {
      siblingManualByProgramme.set(progId, entry);
    }
    const normalized = normalizedNameByProgrammeId.get(progId);
    if (normalized && !siblingManualByName.has(normalized)) {
      siblingManualByName.set(normalized, entry);
    }
  }

  let items = myOfferings
    .map((o) => {
      const progId = String(o.programme);
      const programme = programmeById.get(progId);
      if (!programme) return null;

      const base = { programmeId: progId, programmeName: programme.name, faculty: programme.faculty || "" };

      const ownRule = ownManualByProgramme.get(progId);
      if (ownRule) {
        return { ...base, status: "manual", cutoffMark: ownRule.utme?.minimumScore ?? null, sourceInstitution: null };
      }

      if (tier === null) return { ...base, status: "unmatched", cutoffMark: null, sourceInstitution: null };

      const matrixValue = matrixByKey.get(`${progId}:${tier}`);
      if (matrixValue !== undefined) {
        return { ...base, status: "matrix", cutoffMark: matrixValue, sourceInstitution: null };
      }

      const sibling = siblingManualByProgramme.get(progId);
      if (sibling) {
        return {
          ...base,
          status: "auto",
          matchedBy: "id",
          cutoffMark: sibling.rule.utme?.minimumScore ?? null,
          sourceInstitution: sibling.institution ? { id: String(sibling.institution._id), name: sibling.institution.name } : null,
          sourceProgrammeName: null,
        };
      }

      const normalized = normalizedNameByProgrammeId.get(progId);
      const nameSibling = normalized ? siblingManualByName.get(normalized) : null;
      if (nameSibling) {
        return {
          ...base,
          status: "auto",
          matchedBy: "name",
          cutoffMark: nameSibling.rule.utme?.minimumScore ?? null,
          sourceInstitution: nameSibling.institution
            ? { id: String(nameSibling.institution._id), name: nameSibling.institution.name }
            : null,
          sourceProgrammeName: nameSibling.programme?.name || null,
        };
      }

      return { ...base, status: "unmatched", cutoffMark: null, sourceInstitution: null };
    })
    .filter(Boolean);

  // Close every freshly-found "auto" gap by writing its matrix entry now, so
  // rule generation reads it as a normal MATRIX cutoff from here on. Never
  // touches a cell that already exists (matrixByKey was read before any of
  // these writes), so an admin's own curated value is never overwritten.
  const newlyAutoMapped = items.filter((i) => i.status === "auto");
  if (newlyAutoMapped.length && tier !== null) {
    await Promise.all(
      newlyAutoMapped.map(async (i) => {
        const source = i.sourceInstitution?.name || "a sibling institution";
        const notes =
          i.matchedBy === "name"
            ? `Auto-mapped from ${source}'s published cutoff for "${i.sourceProgrammeName}" (name-matched, not the same catalog id)`
            : `Auto-mapped from ${source}'s published cutoff`;
        const doc = await CourseTierCutoff.findOneAndUpdate(
          { programme: i.programmeId, institutionTier: tier },
          { $setOnInsert: { cutoffMark: i.cutoffMark, notes, updatedBy: actor?._id } },
          { upsert: true, new: true, setDefaultsOnInsert: true }
        );
        await auditService.record({
          user: actor?._id,
          action: "COURSE_TIER_CUTOFF_AUTO_MAPPED",
          resourceType: RESOURCE_TYPES.COURSE_TIER_CUTOFF,
          resourceId: doc._id,
          newValue: { cutoffMark: doc.cutoffMark, notes: doc.notes },
          req,
        });
      })
    );
  }

  if (search) {
    const q = search.toLowerCase();
    items = items.filter((i) => i.programmeName.toLowerCase().includes(q) || i.faculty.toLowerCase().includes(q));
  }
  items.sort((a, b) => a.programmeName.localeCompare(b.programmeName));

  const total = items.length;
  const skip = (page - 1) * limit;

  return {
    institution: { id: String(institution._id), name: institution.name },
    institutionTier: tier,
    tierLabel: tier !== null ? TIER_LABEL_BY_INDEX.get(tier) : null,
    items: items.slice(skip, skip + limit),
    total,
  };
}

module.exports = { listForProgramme, upsertForProgramme, summary, gaps, listForInstitution };
