/**
 * Shared cutoff-coverage vocabulary used by both
 * scripts/rules/generate-admission-rules.js and the admin course-tier-cutoff
 * API, so the two never disagree about what counts as "still auto-generated"
 * or which institution tier an offering falls in.
 */
const { INSTITUTION_TIERS } = require("../config/constants");

const FORMULA_SOURCE_TITLE = "General JAMB subject-combination pattern (auto-generated)";
const MATRIX_SOURCE_TITLE = "Course-tier cutoff matrix (curated)";
const REGENERATABLE_SOURCE_TITLES = new Set([FORMULA_SOURCE_TITLE, MATRIX_SOURCE_TITLE]);

// Coverage status of one institution+programme offering's UTME cutoff:
//  - MANUAL   an admin published/verified a real cutoff for this exact offering
//  - MATRIX   inherited from the CourseTierCutoff matrix for (programme, institution's tier)
//  - UNMAPPED neither exists yet — currently relying on the synthetic formula fallback
const COVERAGE_STATUS = Object.freeze({
  MANUAL: "manual",
  MATRIX: "matrix",
  UNMAPPED: "unmapped",
});

// A rule only counts as script-owned/safe-to-recompute output if it still
// carries one of the script's own source markers and has never been through
// admin verification. Anything else is someone's real data.
function isStillAutoGenerated(rule) {
  return REGENERATABLE_SOURCE_TITLES.has(rule?.source?.title) && !rule?.verification?.lastVerifiedAt;
}

// An institution's competitivenessIndex can be any 0..1 float (e.g. a manual
// admin override), so tier lookups snap to the nearest defined bucket rather
// than requiring an exact match. Returns null if the institution has no index.
function nearestInstitutionTier(index) {
  if (typeof index !== "number") return null;
  let best = null;
  let bestDistance = Infinity;
  for (const tier of INSTITUTION_TIERS) {
    const distance = Math.abs(tier.index - index);
    if (distance < bestDistance) {
      bestDistance = distance;
      best = tier.index;
    }
  }
  return best;
}

// Same "pick the active, non-test session" rule the rule generator uses, so
// admin-facing coverage/gap views agree with what generation would do.
async function resolveDefaultSession(AdmissionSession, sessionArg) {
  if (sessionArg) {
    const named = await AdmissionSession.findById(sessionArg);
    if (!named) throw new Error(`No admission session with id "${sessionArg}"`);
    return named;
  }
  const candidates = await AdmissionSession.find({ isActive: true });
  const real = candidates.filter((s) => !/test/i.test(s.name));
  if (real.length >= 1) return real[0];
  if (candidates.length > 0) return candidates[0];
  return null;
}

module.exports = {
  FORMULA_SOURCE_TITLE,
  MATRIX_SOURCE_TITLE,
  COVERAGE_STATUS,
  isStillAutoGenerated,
  nearestInstitutionTier,
  resolveDefaultSession,
};
