module.exports = {
  Role: require("./Role"),
  User: require("./User"),
  RefreshToken: require("./RefreshToken"),
  StudentProfile: require("./StudentProfile"),
  Institution: require("./Institution"),
  Programme: require("./Programme"),
  InstitutionProgramme: require("./InstitutionProgramme"),
  AdmissionSession: require("./AdmissionSession"),
  AdmissionRule: require("./AdmissionRule"),
  CourseTierCutoff: require("./CourseTierCutoff"),
  Assessment: require("./Assessment"),
  AssessmentRecommendation: require("./AssessmentRecommendation"),
  Payment: require("./Payment"),
  AuditLog: require("./AuditLog"),
  CutoffSource: require("./CutoffSource"),
  CutoffCandidate: require("./CutoffCandidate"),
  CutoffRecord: require("./CutoffRecord"),
  ChatMessage: require("./ChatMessage"),
};
